# Site Configuration
titleBase: Fletch Docs
favicon: favicon.ico

# Social media links
social:
  - name: Github
    url: https://github.com/kartikey321
  - name: X/Twitter
    url: https://x.com/MahawarKartikey