name: fletch_project

packages:
  - apps/**
  - packages/**

scripts:
    analyze:
      run: melos exec -- "dart analyze"
      description: Run `dart analyze` for all packages

    test:
      run: melos exec -- "dart test"
      description: Run `dart test` for all packages

    get:
      run: melos exec -- "dart pub get"
      description: Run `dart pub get` for all packages
