name: dart_express_project

packages:
  - apps/**
  - packages/**

scripts:
    analyze:
      run: melos exec -- "flutter analyze"
      description: Run `flutter analyze` for all packages

    test:
      run: melos exec -- "flutter test"
      description: Run `flutter test` for all packages

    get:
      run: melos exec -- "flutter pub get"
      description: Run `flutter pub get` for all packages
